pipeline{
	agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }
	agent{
	environment{
		registry = "vikaspolicedockerhub/ros-accounting-service"
		registryCredential = "Docker_Hub"
		dockerImage = ''
	}
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn test' 
            }
        }
		stage('Build Image'){
			steps{
                script{
                    sh '''
					cd Accounting-Service
					dockerImage = docker.build registry
				'''
                }
				
			}
		}
		stage('Push Image'){
			steps{	
                script{
                    docker.withRegistry('', registryCredential){
					dockerImage.push("BUILD_NUMBER")
					dockerImage.push('latest')
                }								
			}
		  }
        }
		stage('Deploy to Test'){
			steps{
				sh '''
					docker rm ros-accounting-service || true
					docker run -d --name ros-accounting-service -p 8082:8082 dockerImage:latest
					'''
					}
				}
			}
		}	
      }
